package:
  name: libesrifgdb
  version: "1.5.1"

source:
  # url: https://github.com/Esri/file-geodatabase-api/raw/master/FileGDB_API_1.5.1/FileGDB_API_1_5_1-64gcc51.tar.gz
  # sha256: 1a1b5c417224e8a4dfd3f7c1f4d1911febf1de38e9b6f93a1e4523a9fce92a91
  url: https://github.com/Esri/file-geodatabase-api/raw/master/FileGDB_API_1.5.1/FileGDB_API_1_5_1-64.tar.gz
  sha256: 59b6f70a5662240eec7148936f4f401694162f70edc754d3074b6551582f6fe1
  

build:
  number: 1

requirements:
  build:
  run:

about:
  summary: 'Esri File Geodatabase API'

extra:
  recipe-maintainers:
    - tweitzel
